Repository NOW-SOPT-APP4-KREAM/KREAM-iOS, pull requests merged in 2024-05, with the labels that each got.

#3 [Docs] README 작성 완료
  README.md
Labels: 🍨Docs🍨, 👻민서👻

#16 [Setting] SwiftLint 설정 변경 + 코드 반영 완료
  KREAM/.swiftlint.yml
  KREAM/KREAM/Network/DTO/ResponseDTO/DetailProductResponseDTO.swift
  KREAM/KREAM/Network/Foundation/BaseTargetType.swift
Labels: 🍮Setting🍮, 🍧Style🍧, 👻민서👻

#14 [Feat] Custom navigationController 만들기 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Extension/UITextField+.swift
  KREAM/KREAM/Global/Extension/UIView+.swift
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_alarm.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_alarm.imageset/icn_alarm.svg
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/CustomNavigationView.swift
  KREAM/KREAM/Presentation/TabBar/AppTabBarController.swift
Labels: 🍦Feat🍦, 👻신영👻

#17 [Feat] SearchSegmentControlView 작성 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Utility/Divider.swift
  KREAM/KREAM/Presentation/Components/Reference/PreviewController.swift
  KREAM/KREAM/Presentation/Components/Reference/SomeView.swift
  KREAM/KREAM/Presentation/Components/Reference/SomeViewController.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchSegmentControlView.swift
Labels: 🍦Feat🍦, 👻민서👻

#20 [Feat] SearchFilterTabsView 작성 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/SearchPage/Views/SearchFilterTabsView.swift
Labels: 🍦Feat🍦, 👻민서👻

#22 Feat/#8 item info sticky view
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_scrap.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_scrap.imageset/scraplogo.svg
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ItemInfoStickyView.swift
Labels: 🍦Feat🍦, 👻여경👻

#24 [Feat] SearchResultListView 작성 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/SearchPage/Views/SearchFilterTabsView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchResultListView.swift
Labels: 🍦Feat🍦, 👻민서👻

#26 [Feat] SearchRelatedListView
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/SearchPage/Cells/SearchRelatedCollectionViewCell.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchRelatedListView.swift
Labels: 🍦Feat🍦, 👻민서👻

#28 [Feat] TopSearchBar 작성 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/SearchPage/Views/TopSearchBarView.swift
Labels: 🍦Feat🍦, 👻민서👻

#35 Feat:#23 - InfoTabBarView구현
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_back.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_back.imageset/icn_back.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_addalarm.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_addalarm.imageset/icn_addalarm.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_share.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_share.imageset/icn_share.svg
  KREAM/KREAM/Presentation/DetailInfoPage/Views/InfoTabBarView.swift
Labels: 🍦Feat🍦, 👻여경👻

#32 [Feat] SearchResultViewController 작성 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/SearchPage/ViewController/SearchResultViewController.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchFilterTabsView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchRelatedListView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchResultHeaderView.swift
  KREAM/KREAM/Presentation/TabBar/AppTabBarController.swift
Labels: 🍦Feat🍦, 👻민서👻

#33 [Feat] CustomSegmentedControl 구현 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Color/Colors/Brown.colorset/Contents.json
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/UnderlineSegmentedControl.swift
Labels: 🍦Feat🍦, 👻신영👻

#39 [Feat] ReleaseInfoPageCollectionView 구현 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_scrap_isSelected.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_scrap_isSelected.imageset/icn_scrap_isSelected.svg
  KREAM/KREAM/Presentation/ReleaseInfoPage/Cells/ReleaseCollectionViewCell.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Model/ItemModel.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseCollectionViewController.swift
Labels: 🍦Feat🍦, 👻신영👻

#40 [Feat] CenterChipScrollView 영역 구현 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/CenterChipScrollView.swift
Labels: 🍦Feat🍦, 🍰Fix🍰, 👻신영👻

#42 [Feat]GoodsInfoView구현
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_downarrow.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_downarrow.imageset/icn_downarrow.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_down.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_down.imageset/icn_down.svg
  KREAM/KREAM/Presentation/DetailInfoPage/Model/InfoModel.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/GoodsInfoView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ItemDataStackViewCell.swift
Labels: 🍦Feat🍦, 👻여경👻

#44 [Feat] ProductBenefitView구현
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/DetailInfoPage/Views/GoodsInfoView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ItemDataStackViewCell.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ProductBenefitView.swift
Labels: 🍦Feat🍦, 👻여경👻

#45 [Feat] SearchResultViewController Refine
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_bolt.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_bolt.imageset/icn_bolt.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_grid2.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_grid2.imageset/Property 1=icn_sorting_2.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_grid3.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_grid3.imageset/Property 1=icn_sorting_3.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_magnifier.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_magnifier.imageset/Property 1=dark.svg
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_saved_filled.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Icon/icn_saved_filled.imageset/Property 1=on.svg
  KREAM/KREAM/Network/DTO/ResponseDTO/ProductResponseDTO.swift
  KREAM/KREAM/Network/Router/KreamTargetType.swift
  KREAM/KREAM/Network/Service/APIService.swift
  KREAM/KREAM/Presentation/Components/ItemInfoDetailCollectionViewCell /Model/ItemDetail.swift
  KREAM/KREAM/Presentation/Components/ItemInfoDetailCollectionViewCell /View/ItemDetailCollectionViewCell.swift
  KREAM/KREAM/Presentation/Components/ItemInfoDetailCollectionViewCell /ViewController/testViewController.swift
  KREAM/KREAM/Presentation/SearchPage/Cells/SearchRelatedCollectionViewCell.swift
  KREAM/KREAM/Presentation/SearchPage/ViewController/SearchResultViewController.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchFilterTabsView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchRelatedListView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchResultHeaderView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/SearchResultListView.swift
  KREAM/KREAM/Presentation/SearchPage/Views/TopSearchBarView.swift
Labels: 🍦Feat🍦, 👻민서👻

#50 [Feat] ProductImageView 구현
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ProductImageView.swift
Labels: 🍦Feat🍦, 👻여경👻

#51 [Feat] 각 컴포넌트 ReleaseInfoViewController 연결 및 발매정보 조회 API 구현 완료
  KREAM/KREAM/Network/DTO/ResponseDTO/ReleaseProductResponseDTO.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Cells/ReleaseCollectionViewCell.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Model/ItemModel.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseCollectionViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/CenterChipScrollView.swift
Labels: 🍦Feat🍦, 👻신영👻

#53 [Feat] Scrap 등록, 삭제 API구현 및 ScrapBtn toggle 동작 구현 완료
  KREAM/KREAM/Presentation/ReleaseInfoPage/Cells/ReleaseCollectionViewCell.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseCollectionViewController.swift
Labels: 🍦Feat🍦, 👻신영👻

#55 [Feat] 상단 탭바 구현 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/AnotherScrollView.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/ScrollFitable.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/TabView.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/UnderlineSegmentedControl.swift
Labels: 🍦Feat🍦, 👻신영👻

#58 [Feat] RecommendationViewController 작성 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Presentation/RecommendationPage/ViewController/RecommendationViewController.swift
  KREAM/KREAM/Presentation/RecommendationPage/Views/CardInfoCollectionView.swift
  KREAM/KREAM/Presentation/RecommendationPage/Views/ForYouView.swift
Labels: 🍦Feat🍦, 👻민서👻

#59 [Feat] LuckyDraw 파트 구현 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw1.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw1.imageset/view1_img_ad_01@1x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw1.imageset/view1_img_ad_01@2x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw1.imageset/view1_img_ad_01@3x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw2.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw2.imageset/view1_img_ad_02@1x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw2.imageset/view1_img_ad_02@2x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw2.imageset/view1_img_ad_02@3x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw3.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw3.imageset/view1_img_ad_03@1x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw3.imageset/view1_img_ad_03@2x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw3.imageset/view1_img_ad_03@3x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw4.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw4.imageset/view1_img_ad_04@1x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw4.imageset/view1_img_ad_04@2x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw4.imageset/view1_img_ad_04@3x.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw_Timer.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/lucky_draw_Timer.imageset/luckyDraw_Timer.svg
  KREAM/KREAM/Presentation/ReleaseInfoPage/Cells/LuckyDrawCollectionViewCell.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Cells/ReleaseCollectionViewCell.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/LuckyDrawCollectionViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
Labels: 🍦Feat🍦, 👻신영👻

#62 [Feat] Style collection view구현
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/icn_shoes.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/icn_shoes.imageset/icn_shoes.svg
  KREAM/KREAM/Presentation/DetailInfoPage/Cells/ProductImageCell.swift
  KREAM/KREAM/Presentation/DetailInfoPage/ViewController/ForthViewController.swift
  KREAM/KREAM/Presentation/DetailInfoPage/ViewController/ViewController.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/GoodsInfoView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/InfoTabBarView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/StyleCollectionView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/StyleTopView.swift
Labels: 🍦Feat🍦, 👻여경👻

#63 [Feat] View1 - View2 연결 완료
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
Labels: 🍦Feat🍦, 👻신영👻

#67 [Fix] View1 상품 이미지 비율 개선 완료
  KREAM/KREAM/Presentation/ReleaseInfoPage/Cells/ReleaseCollectionViewCell.swift
Labels: 🍰Fix🍰, 👻신영👻

#69 Feat/#64 api connection
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_shoes1.imageset/Contents.json
  KREAM/KREAM/Global/Resources/Assets.xcassets/Image/icn_shoes1.imageset/icn_shoes1.svg
  KREAM/KREAM/Presentation/DetailInfoPage/Model/InfoModel.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Model/Product.swift
  KREAM/KREAM/Presentation/DetailInfoPage/ViewController/ForthViewController.swift
  KREAM/KREAM/Presentation/DetailInfoPage/ViewController/ViewController.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/GoodsInfoView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/InfoTabBarView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ItemDataStackViewCell.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ItemInfoStickyView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/MoreStyleView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/ProductImageView.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/StyleTopView.swift
Labels: 🍰Fix🍰, 👻여경👻

#70 [Feat] View1,2와 View3 연결 완료
  KREAM/KREAM.xcodeproj/project.pbxproj
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  KREAM/KREAM/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/Views/CustomNavigationView.swift
  KREAM/KREAM/Presentation/SearchPage/ViewController/SearchResultViewController.swift
  KREAM/KREAM/Presentation/SearchPage/Views/TopSearchBarView.swift
  KREAM/KREAM/Presentation/TabBar/AppTabBarController.swift
Labels: 🍦Feat🍦, 👻신영👻

#72 [Feat] 전체 View 연결 완료
  KREAM/KREAM/Presentation/DetailInfoPage/ViewController/ForthViewController.swift
  KREAM/KREAM/Presentation/DetailInfoPage/Views/InfoTabBarView.swift
  KREAM/KREAM/Presentation/ReleaseInfoPage/ViewController/ReleaseInfoPageViewController.swift
  KREAM/KREAM/Presentation/SearchPage/ViewController/SearchResultViewController.swift
  KREAM/KREAM/Presentation/TabBar/AppTabBarController.swift
Labels: 🍦Feat🍦, 👻신영👻
